package com.pe.ripley.validacioncompracoco.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CompraCoCoInput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Tipo de Operacion")
	private java.lang.String tipoOperacion;
	@org.kie.api.definition.type.Label("Canal")
	private java.lang.String canal;
	@org.kie.api.definition.type.Label("Valor de Intentos")
	private java.lang.Integer valorIntentos;
	@org.kie.api.definition.type.Label("Periodo Generacion")
	private java.lang.String periodoGeneracion;
	@org.kie.api.definition.type.Label("Monto Maximo")
	private java.lang.Double montoMaximo;

	private java.lang.String flagContinuaFlujoOuput;

	private java.lang.String flagUltimoIntentoOuput;

	private Double montoOuput;

	private java.lang.String canalNotificacionOuput;

	private Integer maximoPeriodo;

	private java.lang.Integer vigenciaCoCoOuput;

	public CompraCoCoInput() {
	}

	public java.lang.String getTipoOperacion() {
		return this.tipoOperacion;
	}

	public void setTipoOperacion(java.lang.String tipoOperacion) {
		this.tipoOperacion = tipoOperacion;
	}

	public java.lang.String getCanal() {
		return this.canal;
	}

	public void setCanal(java.lang.String canal) {
		this.canal = canal;
	}

	public java.lang.Integer getValorIntentos() {
		return this.valorIntentos;
	}

	public void setValorIntentos(java.lang.Integer valorIntentos) {
		this.valorIntentos = valorIntentos;
	}

	public java.lang.String getPeriodoGeneracion() {
		return this.periodoGeneracion;
	}

	public void setPeriodoGeneracion(java.lang.String periodoGeneracion) {
		this.periodoGeneracion = periodoGeneracion;
	}

	public java.lang.Double getMontoMaximo() {
		return this.montoMaximo;
	}

	public void setMontoMaximo(java.lang.Double montoMaximo) {
		this.montoMaximo = montoMaximo;
	}

	public java.lang.String getFlagContinuaFlujoOuput() {
		return this.flagContinuaFlujoOuput;
	}

	public void setFlagContinuaFlujoOuput(
			java.lang.String flagContinuaFlujoOuput) {
		this.flagContinuaFlujoOuput = flagContinuaFlujoOuput;
	}

	public java.lang.String getFlagUltimoIntentoOuput() {
		return this.flagUltimoIntentoOuput;
	}

	public void setFlagUltimoIntentoOuput(
			java.lang.String flagUltimoIntentoOuput) {
		this.flagUltimoIntentoOuput = flagUltimoIntentoOuput;
	}

	public java.lang.String getCanalNotificacionOuput() {
		return this.canalNotificacionOuput;
	}

	public void setCanalNotificacionOuput(
			java.lang.String canalNotificacionOuput) {
		this.canalNotificacionOuput = canalNotificacionOuput;
	}

	public java.lang.Double getMontoOuput() {
		return this.montoOuput;
	}

	public void setMontoOuput(java.lang.Double montoOuput) {
		this.montoOuput = montoOuput;
	}

	public java.lang.Integer getMaximoPeriodo() {
		return this.maximoPeriodo;
	}

	public void setMaximoPeriodo(java.lang.Integer maximoPeriodo) {
		this.maximoPeriodo = maximoPeriodo;
	}

	public java.lang.Integer getVigenciaCoCoOuput() {
		return this.vigenciaCoCoOuput;
	}

	public void setVigenciaCoCoOuput(java.lang.Integer vigenciaCoCoOuput) {
		this.vigenciaCoCoOuput = vigenciaCoCoOuput;
	}

	public CompraCoCoInput(java.lang.String tipoOperacion,
			java.lang.String canal, java.lang.Integer valorIntentos,
			java.lang.String periodoGeneracion, java.lang.Double montoMaximo,
			java.lang.String flagContinuaFlujoOuput,
			java.lang.String flagUltimoIntentoOuput,
			java.lang.Double montoOuput,
			java.lang.String canalNotificacionOuput,
			java.lang.Integer maximoPeriodo, java.lang.Integer vigenciaCoCoOuput) {
		this.tipoOperacion = tipoOperacion;
		this.canal = canal;
		this.valorIntentos = valorIntentos;
		this.periodoGeneracion = periodoGeneracion;
		this.montoMaximo = montoMaximo;
		this.flagContinuaFlujoOuput = flagContinuaFlujoOuput;
		this.flagUltimoIntentoOuput = flagUltimoIntentoOuput;
		this.montoOuput = montoOuput;
		this.canalNotificacionOuput = canalNotificacionOuput;
		this.maximoPeriodo = maximoPeriodo;
		this.vigenciaCoCoOuput = vigenciaCoCoOuput;
	}

}