package com.pe.ripley.validacioncompracoco.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CompraCoCoOuput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Flag indica ultimo intento")
	private java.lang.String flagUltimoIntento;
	@org.kie.api.definition.type.Label("Monto")
	private java.lang.Double monto;
	@org.kie.api.definition.type.Label("Canal de notificacion")
	private java.lang.String canalNotificacion;

	private java.lang.String estado;

	private java.lang.Integer vigenciaCoCo;

	@org.kie.api.definition.type.Label(value = "Flag indica continua el flujo")
	private java.lang.String flagContinuaFlujo;

	public CompraCoCoOuput() {
	}

	public java.lang.String getFlagUltimoIntento() {
		return this.flagUltimoIntento;
	}

	public void setFlagUltimoIntento(java.lang.String flagUltimoIntento) {
		this.flagUltimoIntento = flagUltimoIntento;
	}

	public java.lang.Double getMonto() {
		return this.monto;
	}

	public void setMonto(java.lang.Double monto) {
		this.monto = monto;
	}

	public java.lang.String getCanalNotificacion() {
		return this.canalNotificacion;
	}

	public void setCanalNotificacion(java.lang.String canalNotificacion) {
		this.canalNotificacion = canalNotificacion;
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public java.lang.Integer getVigenciaCoCo() {
		return this.vigenciaCoCo;
	}

	public void setVigenciaCoCo(java.lang.Integer vigenciaCoCo) {
		this.vigenciaCoCo = vigenciaCoCo;
	}

	public java.lang.String getFlagContinuaFlujo() {
		return this.flagContinuaFlujo;
	}

	public void setFlagContinuaFlujo(java.lang.String flagContinuaFlujo) {
		this.flagContinuaFlujo = flagContinuaFlujo;
	}

	public CompraCoCoOuput(java.lang.String flagUltimoIntento,
			java.lang.Double monto, java.lang.String canalNotificacion,
			java.lang.String estado, java.lang.Integer vigenciaCoCo,
			java.lang.String flagContinuaFlujo) {
		this.flagUltimoIntento = flagUltimoIntento;
		this.monto = monto;
		this.canalNotificacion = canalNotificacion;
		this.estado = estado;
		this.vigenciaCoCo = vigenciaCoCo;
		this.flagContinuaFlujo = flagContinuaFlujo;
	}

}